/// Enumeration of all Quran surahs with their numeric order and Arabic names.
enum QuranSurah {
  alFatiha(1, 'الفاتحة'),
  alBaqarah(2, 'البقرة'),
  aalImran(3, 'آل عمران'),
  anNisa(4, 'النساء'),
  alMaida(5, 'المائدة'),
  alAnam(6, 'الأنعام'),
  alAraf(7, 'الأعراف'),
  alAnfal(8, 'الأنفال'),
  atTawbah(9, 'التوبة'),
  yunus(10, 'يونس'),
  hud(11, 'هود'),
  yusuf(12, 'يوسف'),
  arRad(13, 'الرعد'),
  ibrahim(14, 'إبراهيم'),
  alHijr(15, 'الحجر'),
  anNahl(16, 'النحل'),
  alIsra(17, 'الإسراء'),
  alKahf(18, 'الكهف'),
  maryam(19, 'مريم'),
  taha(20, 'طه'),
  alAnbiya(21, 'الأنبياء'),
  alHajj(22, 'الحج'),
  alMuminun(23, 'المؤمنون'),
  anNur(24, 'النور'),
  alFurqan(25, 'الفرقان'),
  ashShuara(26, 'الشعراء'),
  anNaml(27, 'النمل'),
  alQasas(28, 'القصص'),
  alAnkabut(29, 'العنكبوت'),
  arRum(30, 'الروم'),
  luqman(31, 'لقمان'),
  asSajdah(32, 'السجدة'),
  alAhzab(33, 'الأحزاب'),
  saba(34, 'سبأ'),
  fatir(35, 'فاطر'),
  yaSin(36, 'يس'),
  asSaffat(37, 'الصافات'),
  sad(38, 'ص'),
  azZumar(39, 'الزمر'),
  ghafir(40, 'غافر'),
  fussilat(41, 'فصلت'),
  ashShura(42, 'الشورى'),
  azZukhruf(43, 'الزخرف'),
  adDukhan(44, 'الدخان'),
  alJathiyah(45, 'الجاثية'),
  alAhqaf(46, 'الأحقاف'),
  muhammad(47, 'محمد'),
  alFath(48, 'الفتح'),
  alHujurat(49, 'الحجرات'),
  qaf(50, 'ق'),
  adhDhariyat(51, 'الذاريات'),
  atTur(52, 'الطور'),
  anNajm(53, 'النجم'),
  alQamar(54, 'القمر'),
  arRahman(55, 'الرحمن'),
  alWaqiah(56, 'الواقعة'),
  alHadid(57, 'الحديد'),
  alMujadila(58, 'المجادلة'),
  alHashr(59, 'الحشر'),
  alMumtahanah(60, 'الممتحنة'),
  asSaff(61, 'الصف'),
  alJumuah(62, 'الجمعة'),
  alMunafiqun(63, 'المنافقون'),
  atTaghabun(64, 'التغابن'),
  atTalaq(65, 'الطلاق'),
  atTahrim(66, 'التحريم'),
  alMulk(67, 'الملك'),
  alQalam(68, 'القلم'),
  alHaaqqah(69, 'الحاقة'),
  alMaarij(70, 'المعارج'),
  nuh(71, 'نوح'),
  alJinn(72, 'الجن'),
  alMuzzammil(73, 'المزمل'),
  alMuddaththir(74, 'المدثر'),
  alQiyamah(75, 'القيامة'),
  alInsan(76, 'الإنسان'),
  alMursalat(77, 'المرسلات'),
  anNaba(78, 'النبأ'),
  anNaziat(79, 'النازعات'),
  abasa(80, 'عبس'),
  atTakwir(81, 'التكوير'),
  alInfitar(82, 'الانفطار'),
  alMutaffifin(83, 'المطففين'),
  alInshiqaq(84, 'الانشقاق'),
  alBurooj(85, 'البروج'),
  atTariq(86, 'الطارق'),
  alAla(87, 'الأعلى'),
  alGhashiyah(88, 'الغاشية'),
  alFajr(89, 'الفجر'),
  alBalad(90, 'البلد'),
  ashShams(91, 'الشمس'),
  alLayl(92, 'الليل'),
  adDuha(93, 'الضحى'),
  ashSharh(94, 'الشرح'),
  atTin(95, 'التين'),
  alAlaq(96, 'العلق'),
  alQadr(97, 'القدر'),
  alBayyinah(98, 'البينة'),
  azZalzalah(99, 'الزلزلة'),
  alAdiyat(100, 'العاديات'),
  alQariah(101, 'القارعة'),
  atTakathur(102, 'التكاثر'),
  alAsr(103, 'العصر'),
  alHumazah(104, 'الهمزة'),
  alFil(105, 'الفيل'),
  quraish(106, 'قريش'),
  alMaun(107, 'الماعون'),
  alKawthar(108, 'الكوثر'),
  alKafirun(109, 'الكافرون'),
  anNasr(110, 'النصر'),
  alMasad(111, 'المسد'),
  alIkhlas(112, 'الإخلاص'),
  alFalaq(113, 'الفلق'),
  anNas(114, 'الناس');

  const QuranSurah(this.number, this.arabicName);

  /// The surah order in the Quran.
  final int number;

  /// The surah name in Arabic for display.
  final String arabicName;

  /// Finds a surah by its numeric order. Returns `null` when not found.
  static QuranSurah? fromNumber(int number) {
    for (final surah in QuranSurah.values) {
      if (surah.number == number) return surah;
    }
    return null;
  }
}
